apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdotnet5-deplpoyment
spec:
  selector:
    matchLabels:
      app: catalogdotnet5
  template:
    metadata:
      labels:
        app: catalogdotnet5
    spec:
      containers:
      - name: catalogdotnet5
        image: catalogdotnet5:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MongoDbSettings__Host
          value: mongodb-service
        - name: MongoDbSettings__Password
          valueFrom:
            secretKeyRef:
              name: catalog-secrets
              key: mongodb-password 
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalogdotnet5
  ports:
  - port: 80
    targetPort: 80
